[project]
name = "ai-multisense"
version = "1.0.0"
requires-python = ">=3.11, <3.12"

[tool.pyright]
include = ["backend", "ai", "tests"]
executionEnvironments = [
  { root = "." }
]
extraPaths = ["."]
venvPath = "."
venv = "venv"
pythonVersion = "3.11"
typeCheckingMode = "basic"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
